---
# tasks file for ansible-hosts

- name: /etc/hosts
  become: true
  ansible.builtin.blockinfile:
    path: /etc/hosts
    marker: "# {mark} /etc/hosts - ANSIBLE MANAGED BLOCK"
    block: |
      192.168.5.10    DS1819
      192.168.5.10    DS1819.local

- name: Install stormssh into ansible's python packages
  ansible.builtin.pip:
    name: stormssh
    executable: "{{ ansible_facts.python.executable | replace('python', 'pip') }}"

- name: Create ~/.ssh if directory does not exist
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.ssh"
    state: directory
    mode: "0700"

- name: Add hosts to ~/.ssh/config
  community.general.ssh_config:
    ssh_config_file: "{{ ansible_env.HOME }}/.ssh/config"
    host: "{{ item.host }}"
    hostname: "{{ item.ip }}"
    remote_user: "{{ item.user|default('root') }}"
    port: "{{ item.port|default(22) }}"
    forward_agent: "{{ item.forward|default(false) }}"
    state: present
  loop: "{{ ssh_config }}"
  when: ssh_config|default([])|count > 0
