---
# tasks file for ansible-hosts

- name: /etc/hosts
  become: true
  ansible.builtin.blockinfile:
    path: /etc/hosts
    marker: "# {mark} /etc/hosts - ANSIBLE MANAGED BLOCK"
    block: |
      192.168.5.1     pfsense
      192.168.5.1     pfsense.local
      192.168.5.10    DS1819
      192.168.5.10    DS1819.local
      192.168.5.15    vsphere
      192.168.5.15    vsphere.local

- name: Install stormssh into ansible's python packages
  ansible.builtin.pip:
    name: stormssh
    executable: "{{ ansible_facts.python.executable | replace('python', 'pip') }}"

- name: Create ~/.ssh if directory does not exist
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.ssh"
    state: directory
    mode: 0700

- name: Add aida to ~/.ssh/config
  community.general.ssh_config:
    ssh_config_file: "{{ ansible_env.HOME }}/.ssh/config"
    host: aida
    hostname: 192.168.5.20
    remote_user: nik
    port: "22"
    state: present
