---
# tasks file for ansible-hosts

- name: /etc/hosts
  become: true
  blockinfile:
    path: "/etc/hosts"
    marker: "# {mark} /etc/hosts - ANSIBLE MANAGED BLOCK"
    block: |
      192.168.5.1     pfsense
      192.168.5.1     pfsense.local
      192.168.5.10    DS1819
      192.168.5.10    DS1819.local
      192.168.5.15    vsphere
      192.168.5.15    vsphere.local
